# Generated by Django 4.1.1 on 2022-11-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_review_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='image',
            field=models.ImageField(upload_to='item_type'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(upload_to='items'),
        ),
    ]
