# Generated by Django 4.1.1 on 2022-11-16 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_remove_media_is_featured_item_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
